name: CI-CD SimpleWebAPI Martes

on:
  push:
    branches: [ "main" ]

env:
  BUILD_CONFIGURATION: Release
  PROJECT_PATH: SimpleWebAPI/SimpleWebAPI.csproj
  WEBAPP_QA: Clima2025v-github         # <- tu WebApp QA

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: .NET 7.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '7.x'

      - name: Cache NuGet
        uses: actions/cache@v4
        with:
          # cacheamos la ruta por defecto que usa dotnet (/home/runner/.nuget/packages)
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json','**/*.csproj') }}
          restore-keys: |
            nuget-${{ runner.os }}-
            nuget-

      - name: Restore
        run: dotnet restore "${{ env.PROJECT_PATH }}"

      - name: Build
        run: dotnet build "${{ env.PROJECT_PATH }}" -c ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Publish
        run: dotnet publish "${{ env.PROJECT_PATH }}" -c ${{ env.BUILD_CONFIGURATION }} -o ./publish --no-build

      - name: Zip package
        run: |
          cd publish
          zip -r ../site.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: miback
          path: site.zip

  deploy_qa:
    runs-on: ubuntu-latest
    needs: build
    environment: QA
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: miback
          path: ./artifact

      - name: Deploy to Azure WebApp (QA)
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_QA }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_QA_VIERNES }}
          package: ./artifact/site.zip
